name: Rutaxruta CI
on:
  push:
    branches: [ master ]
jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21
      - uses: extractions/setup-just@v1          
      - name: Test
        run: just
      - name: Set up Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install npm packages
        working-directory: ruta-frontend
        run: npm install
      - name: Build ruta-frontend
        working-directory: ruta-frontend
        run: npm run build
